# See CKAN docs on installation from Docker Compose on usage
FROM debian:buster
MAINTAINER Carlo Cancellieri



# Install required system packages
RUN apt-get -q -y update \
    && DEBIAN_FRONTEND=noninteractive apt-get -q -y upgrade \
    && apt-get -q -y install \
        python-dev \
        python-pip \
        python-virtualenv \
        python-wheel \
        libpq-dev \
        libxml2-dev \
        libxslt-dev \
        libgeos-dev \
        libssl-dev \
        libffi-dev \
        postgresql-client \
        build-essential \
        git-core \
        vim \
        wget \
    && apt-get -q clean \
    && rm -rf /var/lib/apt/lists/*

# Define environment variables
ENV CKAN_HOME /usr/lib/ckan
ENV CKAN_VENV $CKAN_HOME/venv
ENV CKAN_CONFIG /etc/ckan
ENV CKAN_STORAGE_PATH /var/lib/ckan

# Build-time variables specified by docker-compose.yml / .env
ARG CKAN_SITE_URL
ARG PLUGIN

# Create ckan user
RUN useradd -r -u 900 -m -c "ckan account" -d $CKAN_HOME -s /bin/false ckan

# Setup virtual environment for CKAN
RUN mkdir -p $CKAN_VENV $CKAN_CONFIG $CKAN_STORAGE_PATH && \
    virtualenv $CKAN_VENV && \
    ln -s $CKAN_VENV/bin/pip /usr/local/bin/ckan-pip &&\
    ln -s $CKAN_VENV/bin/paster /usr/local/bin/ckan-paster

# Virtual environment binaries/scripts to be used first
ENV PATH=${CKAN_VENV}/bin:${PATH}  

# Setup CKAN
ADD ./ckan $CKAN_VENV/src/ckan/
ADD . $CKAN_VENV/src/ckanext-${PLUGIN}
# ADD . $CKAN_VENV/src/${PLUGIN}

# RUN ls -la $CKAN_VENV/src/ckan
# RUN ls -la $CKAN_VENV/src/${PLUGIN}

RUN ckan-pip install -U 'pip<21' && \
    ckan-pip install --upgrade --no-cache-dir -r $CKAN_VENV/src/ckan/requirement-setuptools.txt && \
    ckan-pip install --upgrade --no-cache-dir -r $CKAN_VENV/src/ckan/requirements.txt && \
    ckan-pip install -e $CKAN_VENV/src/ckan/ && \
    ln -s $CKAN_VENV/src/ckan/ckan/config/who.ini $CKAN_CONFIG/who.ini && \
    cp -v $CKAN_VENV/src/ckan/contrib/docker/ckan-entrypoint.sh /ckan-entrypoint.sh && \
    chmod +x /ckan-entrypoint.sh && \
    chown -R ckan:ckan $CKAN_HOME $CKAN_VENV $CKAN_CONFIG $CKAN_STORAGE_PATH

ENTRYPOINT ["/ckan-entrypoint.sh"]

RUN ckan-pip install --upgrade --no-cache-dir -r $CKAN_VENV/src/ckan/dev-requirements.txt && \
    ckan-pip install --upgrade --no-cache-dir pytest-ckan

RUN ckan-pip install --upgrade --no-cache-dir -r $CKAN_VENV/src/ckanext-$PLUGIN/dev-requirements.txt && \
    ckan-pip install --upgrade --no-cache-dir -r $CKAN_VENV/src/ckanext-$PLUGIN/requirements.txt

ENV RUN_TEST $CKAN_VENV/src/ckanext-$PLUGIN/run-test.sh
# ENV RUN_TEST $CKAN_VENV/src/$PLUGIN/run-test.sh

# Arg is not persistent, let's pass PLUGIN to docker run
ENV PLUGIN=${PLUGIN}
RUN chmod +x $RUN_TEST

USER ckan
# EXPOSE 5000

CMD ["sh","-c","$RUN_TEST"]
